### ISSUE TITLE
maybe something wrong with monitor

### ISSUE THREAD

**Issue by leebaok** [unias/docklet#112]
After several times of starting/stopping workspace, there will be a WARNING like below

```
2016-05-18 13:52:58,521 WARNING  monitor[320] Traceback (most recent call last):
  File "/home/leebaok/Project/docklet-leebaok/src/monitor.py", line 311, in run
    info = list(eval(worker.workerFetchInfo()))
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1089, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1429, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1131, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1143, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1249, in send_request
    connection.putrequest("POST", handler, skip_accept_encoding=True)
  File "/usr/lib/python3.5/http/client.py", line 966, in putrequest
    raise CannotSendRequest(self.__state)
http.client.CannotSendRequest: Request-sent
```

Is it fine ?

**Comment by FirmlyReality** [comment]
I think it's ok.
